import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StateContextProvider from "@/context/state.context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pixabay Image Search",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StateContextProvider>{children}</StateContextProvider>
      </body>
    </html>
  );
}
